


// historiaClinicaBody.js
// Objeto base de la historia clínica (sin token, talla y peso se pasan después)
const getHistoriaClinicaBody = ({ talla = "170", peso = "68.5" } = {}) => ({
    id_historia: "3050593",
    numero_historia: "",
    hora_historia: "15:31",
    fk_servicio_ingreso: "4",
    fk_admision: "6638184",
    facturacion_admisiones: {
        fk_paciente: "1075687",
        numero_admision: "248652",
        nombre_acompanante: "Nombre responsable",
        direccion_acompanante: "Direccion acompañante",
        telefono_acompanante: "3137554568",
        nombre_responsable: "Nombre responsable",
        parentesco_responsable: "Nombre responsable",
        telefono_responsable: "Nombre responsable",
        pacientes: {
            direccion_paciente: "CRR 13 CLL 16B -36",
            fk_ocupacion: "999",
            fk_nivel_educativo: "13",
            fk_grupo_etnico: "6",
            fk_discapacidad: "6",
            EnfoqueDiferencialIdGenero: "1",
            IdOrientacionSexualEnfoqueDiferencial: "5",
        }
    },
    fk_procedimiento: "8140",
    motivo_consulta_historia: "Motivo consulta (breve descripción)\n",
    fk_finalidad_consulta: "12",
    IdActividad: "10",
    enfermedad_actual_historia: "Motivo consulta (breve descripción)\n",
    
    // Talla y peso se asignarán dinámicamente desde el controlador
    hallazgos_fisicos_signos_vitales_talla_historia: talla,
    hallazgos_fisicos_signos_vitales_peso_historia: peso,
    hallazgos_fisicos_otros_cabeza_historia: "NORMOCEFALO, PUPILAS ISOCORICAS NORMOREACTIVAS A LA LUZ, FOSAS NASALES PERMEABLES, CAVIDAD ORAL NORMAL",
    hallazgos_fisicos_otros_cuello_historia: "SIMETRICO, MOVIL, NO ADENOPATIAS, NO INGURGITACION YUGULAR",
    hallazgos_fisicos_otros_torax_historia: "SIMETRICO, NO DEFORMIDADES, RSCS: RITMICOS, NO SOPLOS, BIEN TIMBRADOS; CSPS: VENTILADOS, NO ESTERTORES",
    hallazgos_fisicos_otros_abdomen_historia: "BLANDO, DEPRESIBLE, NO MASAS PALPABLES, NO VICEROMEGALIAS, NO DOLOROSO A LA PALPACION, RSHS: NORMALES",
    hallazgos_fisicos_otros_genitourinario_historia: "GENITALES EXTERNOS NORMALES, PUÑOPERCUSION NEGATIVA",
    hallazgos_fisicos_otros_pelvis_historia: "SIMETRICA, NO DEFORMIDADES, BUENA MOVILIDAD COXOFEMORAL",
    hallazgos_fisicos_otros_dorso_historia: "SIMETRICAS, NO DEFORMIDADES, NO EDEMAS",
    hallazgos_fisicos_otros_neurologico_historia: "GLASGOW 15/15, CONCIENTE, ORIENTADO EN TIEMPO Y ESPACIO, MOTRICIDAD Y SENSIBILIDAD GENERAL CONSERVADAS",
    hallazgos_fisicos_otros_piel_historia: "HIDRATADA, ASPECTO Y COLORACION NORMAL, SIN LESIONES",
    hallazgos_fisicos_otros_otro_historia: "EMUNTORIOS NORMALES",
    examen_odontologico_tejidos_blandos: "SANO",
    examen_odontologico_paladar: "SANO",
    examen_odontologico_lengua: "SANO",
    examen_odontologico_piso_boca: "SANO",
    examen_odontologico_frenillo_labial_superior: "1",
    examen_odontologico_frenillo_labial_inferior: "1",
    examen_odontologico_frenillo_lingual: "1",
    examen_odontologico_anomalia_esmalte_dentina: "Sin alteraciones",
    examen_odontologico_observaciones: "",
    evoluciones_odontologia: "",
    diagnostico_ingreso_tipo_historia: "1",
    diagnostico_ingreso_fk_causa_externa: "21",
    diagnostico_ingreso_observaciones_historia: "observaciones",


    historia_clinica_enfermedades_diagnostico_ingreso: [
        { id_historia_enfermedad_diagnostico_ingreso: 0, fk_historia: 0, fk_enfermedad: "A000", fk_institucion: 0 }
    ],


    diagnostico_principales_observaciones_consulta_externa: "observaciones",
    diagnostico_relacional_observaciones_historia: "observaciones",



    historia_clinica_odontograma: [
        {
            id_odontograma: null,
            arriba_18: "2", izquierdo_18: "", debajo_18: "", derecha_18: "", centro_18: "3",
            arriba_17: "", izquierdo_17: "4", debajo_17: "", derecha_17: "", centro_17: "",
            arriba_16: "1", izquierdo_16: "5", debajo_16: "", derecha_16: "", centro_16: "",
            arriba_15: "", izquierdo_15: "", debajo_15: "22", derecha_15: "", centro_15: "",
            arriba_14: "23", izquierdo_14: "23", debajo_14: "23", derecha_14: "23", centro_14: "23",
            arriba_13: "24", izquierdo_13: "24", debajo_13: "24", derecha_13: "24", centro_13: "24",
            arriba_12: "25", izquierdo_12: "25", debajo_12: "25", derecha_12: "25", centro_12: "25",
            arriba_11: "", izquierdo_11: "", debajo_11: "", derecha_11: "", centro_11: "",
            arriba_21: "", izquierdo_21: "", debajo_21: "", derecha_21: "", centro_21: "",
            arriba_22: "", izquierdo_22: "", debajo_22: "", derecha_22: "", centro_22: "",
            arriba_23: "", izquierdo_23: "", debajo_23: "", derecha_23: "", centro_23: "",
            arriba_24: "", izquierdo_24: "", debajo_24: "", derecha_24: "", centro_24: "",
            arriba_25: "", izquierdo_25: "", debajo_25: "", derecha_25: "", centro_25: "",
            arriba_26: "", izquierdo_26: "", debajo_26: "", derecha_26: "", centro_26: "",
            arriba_27: "", izquierdo_27: "", debajo_27: "", derecha_27: "", centro_27: "",
            arriba_28: "", izquierdo_28: "", debajo_28: "", derecha_28: "", centro_28: "",
            arriba_55: "", izquierdo_55: "", debajo_55: "", derecha_55: "", centro_55: "",
            arriba_54: "", izquierdo_54: "", debajo_54: "", derecha_54: "", centro_54: "",
            arriba_53: "", izquierdo_53: "", debajo_53: "", derecha_53: "", centro_53: "",
            arriba_52: "", izquierdo_52: "", debajo_52: "", derecha_52: "", centro_52: "",
            arriba_51: "", izquierdo_51: "", debajo_51: "", derecha_51: "", centro_51: "",
            arriba_61: "", izquierdo_61: "", debajo_61: "", derecha_61: "", centro_61: "",
            arriba_62: "", izquierdo_62: "", debajo_62: "", derecha_62: "", centro_62: "",
            arriba_63: "", izquierdo_63: "", debajo_63: "", derecha_63: "", centro_63: "",
            arriba_64: "", izquierdo_64: "", debajo_64: "", derecha_64: "", centro_64: "",
            arriba_65: "", izquierdo_65: "", debajo_65: "", derecha_65: "", centro_65: "",
            arriba_85: "", izquierdo_85: "", debajo_85: "", derecha_85: "", centro_85: "",
            arriba_84: "", izquierdo_84: "", debajo_84: "", derecha_84: "", centro_84: "",
            arriba_83: "", izquierdo_83: "", debajo_83: "", derecha_83: "", centro_83: "",
            arriba_82: "", izquierdo_82: "", debajo_82: "", derecha_82: "", centro_82: "",
            arriba_81: "", izquierdo_81: "", debajo_81: "", derecha_81: "", centro_81: "",
            arriba_71: "", izquierdo_71: "", debajo_71: "", derecha_71: "", centro_71: "",
            arriba_72: "", izquierdo_72: "", debajo_72: "", derecha_72: "", centro_72: "",
            arriba_73: "", izquierdo_73: "", debajo_73: "", derecha_73: "", centro_73: "",
            arriba_74: "", izquierdo_74: "", debajo_74: "", derecha_74: "", centro_74: "",
            arriba_75: "", izquierdo_75: "", debajo_75: "", derecha_75: "", centro_75: "",
            arriba_48: "", izquierdo_48: "", debajo_48: "", derecha_48: "", centro_48: "",
            arriba_47: "", izquierdo_47: "", debajo_47: "", derecha_47: "", centro_47: "",
            arriba_46: "", izquierdo_46: "", debajo_46: "", derecha_46: "", centro_46: "",
            arriba_45: "", izquierdo_45: "", debajo_45: "", derecha_45: "", centro_45: "",
            arriba_44: "", izquierdo_44: "", debajo_44: "", derecha_44: "", centro_44: "",
            arriba_43: "", izquierdo_43: "", debajo_43: "", derecha_43: "", centro_43: "",
            arriba_42: "", izquierdo_42: "", debajo_42: "", derecha_42: "", centro_42: "",
            arriba_41: "", izquierdo_41: "", debajo_41: "", derecha_41: "", centro_41: "",
            arriba_31: "", izquierdo_31: "", debajo_31: "", derecha_31: "", centro_31: "",
            arriba_32: "", izquierdo_32: "", debajo_32: "", derecha_32: "", centro_32: "",
            arriba_33: "", izquierdo_33: "", debajo_33: "", derecha_33: "", centro_33: "",
            arriba_34: "", izquierdo_34: "", debajo_34: "", derecha_34: "", centro_34: "",
            arriba_35: "", izquierdo_35: "", debajo_35: "", derecha_35: "", centro_35: "",
            arriba_36: "", izquierdo_36: "", debajo_36: "", derecha_36: "", centro_36: "",
            arriba_37: "", izquierdo_37: "", debajo_37: "", derecha_37: "", centro_37: "",
            arriba_38: "", izquierdo_38: "", debajo_38: "", derecha_38: "", centro_38: "",
            cop_odntograma: "",
            totalDientesOdontograma: "6",
            fk_institucion: 0
        }
    ],
    historia_clinica_placa_bacteriana: [
        {
            id_placa_bacteria: null,
            arriba_18_bacteriana: "1", izquierdo_18_bacteriana: "", debajo_18_bacteriana: "", derecha_18_bacteriana: "",
            arriba_17_bacteriana: "", izquierdo_17_bacteriana: "", debajo_17_bacteriana: "", derecha_17_bacteriana: "",
            arriba_16_bacteriana: "", izquierdo_16_bacteriana: "", debajo_16_bacteriana: "", derecha_16_bacteriana: "",
            arriba_15_bacteriana: "2", izquierdo_15_bacteriana: "2", debajo_15_bacteriana: "2", derecha_15_bacteriana: "2",
            arriba_14_bacteriana: "", izquierdo_14_bacteriana: "", debajo_14_bacteriana: "", derecha_14_bacteriana: "",
            arriba_13_bacteriana: "24", izquierdo_13_bacteriana: "24", debajo_13_bacteriana: "24", derecha_13_bacteriana: "24",
            arriba_12_bacteriana: "", izquierdo_12_bacteriana: "", debajo_12_bacteriana: "", derecha_12_bacteriana: "",
            arriba_11_bacteriana: "", izquierdo_11_bacteriana: "", debajo_11_bacteriana: "", derecha_11_bacteriana: "",
            arriba_21_bacteriana: "", izquierdo_21_bacteriana: "", debajo_21_bacteriana: "", derecha_21_bacteriana: "",
            arriba_22_bacteriana: "", izquierdo_22_bacteriana: "", debajo_22_bacteriana: "", derecha_22_bacteriana: "",
            arriba_23_bacteriana: "", izquierdo_23_bacteriana: "", debajo_23_bacteriana: "", derecha_23_bacteriana: "",
            arriba_24_bacteriana: "", izquierdo_24_bacteriana: "", debajo_24_bacteriana: "", derecha_24_bacteriana: "",
            arriba_25_bacteriana: "", izquierdo_25_bacteriana: "", debajo_25_bacteriana: "", derecha_25_bacteriana: "",
            arriba_26_bacteriana: "", izquierdo_26_bacteriana: "", debajo_26_bacteriana: "", derecha_26_bacteriana: "",
            arriba_27_bacteriana: "", izquierdo_27_bacteriana: "", debajo_27_bacteriana: "", derecha_27_bacteriana: "",
            arriba_28_bacteriana: "", izquierdo_28_bacteriana: "", debajo_28_bacteriana: "", derecha_28_bacteriana: "",
            arriba_55_bacteriana: "", izquierdo_55_bacteriana: "", debajo_55_bacteriana: "", derecha_55_bacteriana: "",
            arriba_54_bacteriana: "", izquierdo_54_bacteriana: "", debajo_54_bacteriana: "", derecha_54_bacteriana: "",
            arriba_53_bacteriana: "", izquierdo_53_bacteriana: "", debajo_53_bacteriana: "", derecha_53_bacteriana: "",
            arriba_52_bacteriana: "", izquierdo_52_bacteriana: "", debajo_52_bacteriana: "", derecha_52_bacteriana: "",
            arriba_51_bacteriana: "", izquierdo_51_bacteriana: "", debajo_51_bacteriana: "", derecha_51_bacteriana: "",
            arriba_61_bacteriana: "", izquierdo_61_bacteriana: "", debajo_61_bacteriana: "", derecha_61_bacteriana: "",
            arriba_62_bacteriana: "", izquierdo_62_bacteriana: "", debajo_62_bacteriana: "", derecha_62_bacteriana: "",
            arriba_63_bacteriana: "", izquierdo_63_bacteriana: "", debajo_63_bacteriana: "", derecha_63_bacteriana: "",
            arriba_64_bacteriana: "", izquierdo_64_bacteriana: "", debajo_64_bacteriana: "", derecha_64_bacteriana: "",
            arriba_65_bacteriana: "", izquierdo_65_bacteriana: "", debajo_65_bacteriana: "", derecha_65_bacteriana: "",
            arriba_85_bacteriana: "", izquierdo_85_bacteriana: "", debajo_85_bacteriana: "", derecha_85_bacteriana: "",
            arriba_84_bacteriana: "", izquierdo_84_bacteriana: "", debajo_84_bacteriana: "", derecha_84_bacteriana: "",
            arriba_83_bacteriana: "", izquierdo_83_bacteriana: "", debajo_83_bacteriana: "", derecha_83_bacteriana: "",
            arriba_82_bacteriana: "", izquierdo_82_bacteriana: "", debajo_82_bacteriana: "", derecha_82_bacteriana: "",
            arriba_81_bacteriana: "", izquierdo_81_bacteriana: "", debajo_81_bacteriana: "", derecha_81_bacteriana: "",
            arriba_71_bacteriana: "", izquierdo_71_bacteriana: "", debajo_71_bacteriana: "", derecha_71_bacteriana: "",
            arriba_72_bacteriana: "", izquierdo_72_bacteriana: "", debajo_72_bacteriana: "", derecha_72_bacteriana: "",
            arriba_73_bacteriana: "", izquierdo_73_bacteriana: "", debajo_73_bacteriana: "", derecha_73_bacteriana: "",
            arriba_74_bacteriana: "", izquierdo_74_bacteriana: "", debajo_74_bacteriana: "", derecha_74_bacteriana: "",
            arriba_75_bacteriana: "", izquierdo_75_bacteriana: "", debajo_75_bacteriana: "", derecha_75_bacteriana: "",
            arriba_48_bacteriana: "", izquierdo_48_bacteriana: "", debajo_48_bacteriana: "", derecha_48_bacteriana: "",
            arriba_47_bacteriana: "", izquierdo_47_bacteriana: "", debajo_47_bacteriana: "", derecha_47_bacteriana: "",
            arriba_46_bacteriana: "", izquierdo_46_bacteriana: "", debajo_46_bacteriana: "", derecha_46_bacteriana: "",
            arriba_45_bacteriana: "", izquierdo_45_bacteriana: "", debajo_45_bacteriana: "", derecha_45_bacteriana: "",
            arriba_44_bacteriana: "", izquierdo_44_bacteriana: "", debajo_44_bacteriana: "", derecha_44_bacteriana: "",
            arriba_43_bacteriana: "", izquierdo_43_bacteriana: "", debajo_43_bacteriana: "", derecha_43_bacteriana: "",
            arriba_42_bacteriana: "", izquierdo_42_bacteriana: "", debajo_42_bacteriana: "", derecha_42_bacteriana: "",
            arriba_41_bacteriana: "", izquierdo_41_bacteriana: "", debajo_41_bacteriana: "", derecha_41_bacteriana: "",
            arriba_31_bacteriana: "", izquierdo_31_bacteriana: "", debajo_31_bacteriana: "", derecha_31_bacteriana: "",
            arriba_32_bacteriana: "", izquierdo_32_bacteriana: "", debajo_32_bacteriana: "", derecha_32_bacteriana: "",
            arriba_33_bacteriana: "", izquierdo_33_bacteriana: "", debajo_33_bacteriana: "", derecha_33_bacteriana: "",
            arriba_34_bacteriana: "", izquierdo_34_bacteriana: "", debajo_34_bacteriana: "", derecha_34_bacteriana: "",
            arriba_35_bacteriana: "", izquierdo_35_bacteriana: "", debajo_35_bacteriana: "", derecha_35_bacteriana: "",
            arriba_36_bacteriana: "", izquierdo_36_bacteriana: "", debajo_36_bacteriana: "", derecha_36_bacteriana: "",
            arriba_37_bacteriana: "", izquierdo_37_bacteriana: "", debajo_37_bacteriana: "", derecha_37_bacteriana: "",
            arriba_38_bacteriana: "", izquierdo_38_bacteriana: "", debajo_38_bacteriana: "", derecha_38_bacteriana: "",
            porcentaje_placa_bacteriana: 0.81,
            interpretacion_placa_bacteriana: "1",
            fk_institucion: 0
        }
    ],
    analisis_historia: "",
    signos_de_alarma_educacion: "",
    observaciones_historia: "",
    observaciones_odontograma: "observaciones odontograma",
    plan_tratamiento_descripcion_historia: "",
    observaciones_placa_bacteriana: "observaciones placa bacteriana",
    fk_paciente: "1075687",
    telefono_paciente: "0",
    numero_admision: "248652",
    fk_factura_consultas: "5973642",
    motivo_consulta_consulta_externa: "Motivo consulta (breve descripción)\n",
});

module.exports = { getHistoriaClinicaBody };